channels:
  - conda-forge
dependencies:
  - movement>=0.17.0
  - napari
  - pyqt6
  - jupyter
  - python=3.13 # SLEAP v1.6.3 doesn't support Python 3.14 yet
  # Tools for development
  - pre-commit
  - ruff
  - codespell
  - jupyter-cache
